Audio only and video only mode
Eyevinn/webrtc-player pull request #59
Opened 2023-09-13 17:26 UTC by shovtyuk

Added options for audio/video-only mode, and this mode supports WHEPAdapter. Added fallback to audio-only mode after attempting video-only mode in case the server returns a 406 error.

2023-09-13 18:35 UTC, birme requested changes
Thank you for the contribution! Much appreciated.
Just some requested changes on the implementation that I would like to have addressed.

2023-09-13 18:35 UTC, birme commented on src/index.ts
> +export interface WebRTCPlayerOptions {
I am not a fan of passing through the WebRTCPlayerOptions interface directly down to the adapters. I would suggest to add a new type of option interface for example:

```
export interface MediaConstraints {
  audioOnly: boolean;
  videoOnly: boolean;
}
```
and then in the WebRTCPlayerOptions interface
```
interface WebRTCPlayerOptions {
...
  mediaConstraints?: MediaConstraints;
}
```
and then add to the AdapterFactoryFunction:
```
...
onError: (error: string) => void;
mediaConstraints: MediaConstraints;
```

2023-09-13 18:35 UTC, birme commented on src/index.ts
> +    this.opts = opts;
change to:
```
this.mediaConstraints = opts.mediaConstraints;
```

2023-09-13 18:35 UTC, birme commented on src/index.ts
> +  private opts: WebRTCPlayerOptions;
change to
```
private mediaConstraints: MediaConstraints;
```

2023-09-13 18:35 UTC, birme commented on src/index.ts
> +        this.opts
change to `this.mediaConstraints`

2023-09-13 18:40 UTC, birme commented
A general question based on that I haven't really understood the client-initiated approach of WHEP (and I am aware that in recent revision of the standard the server-initiated approach has been removed). 

In what scenarios does the client know that it should expect video-only? Or is the idea it should try and the server respond 406 if not supported? Having a server-initiated SDP exchange it could in the POST request indicate to the player that it should expect video only for example.

2023-09-15 01:16 UTC, shovtyuk commented
Hello! Thanks for the constructive comments! I completely agree and have made the appropriate changes.
In general, the essence of the PR is to give the user the opportunity to play only audio (or only video), regardless of what the server can provide (if it can, of course). The 406 approach is not familiar to me, I just expanded the already existing approach implemented in the code with playing only video in case 406 to a similar retry with only audio.

2023-09-15 04:01 UTC, birme requested changes
Perfect! Just a small thing but could you also add this new option to the documentation?

2023-09-18 15:49 UTC, birme approved these changes

2023-09-18 15:49 UTC, shovtyuk commented
Sure! done)

2023-09-18 15:49 UTC, merged

2023-09-18 15:50 UTC, shovtyuk commented
Thank you!